FROM php:8.3-cli

WORKDIR /var/www/html

# install system packages
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libpng-dev \
    libzip-dev \
    libonig-dev \
    nodejs \
    npm

# install php extensions
RUN docker-php-ext-install \
    pdo_mysql \
    mbstring \
    zip \
    gd

# install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

EXPOSE 8000
EXPOSE 5173

CMD php artisan serve --host=0.0.0.0 --port=8000